{% set name = "dask-ctl" %}
{% set version = "2022.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e3ce221cf042eeca78f012e34646f02de029bdafbc7e1c0363c17bfc5ee2db3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - daskctl=dask_ctl.cli:daskctl

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - dask
    - distributed
    - tornado
    - rich

test:
  imports:
    - dask_ctl

about:
  home: https://github.com/dask-contrib/dask-ctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of tools to provide a control plane for managing the lifecycle of Dask clusters.
  description: |
    A set of tools to provide a control plane for managing the lifecycle of Dask clusters.
  doc_url: https://github.com/dask-contrib/dask-ctl
  dev_url: https://github.com/dask-contrib/dask-ctl

extra:
  recipe-maintainers:
    - jacobtomlinson
