{% set name = "dask-ctl" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5c98011a7387af845fb9d43c2e4224e67cf3be457895e6ae37ef41597e22407

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - daskctl=dask_ctl.cli:daskctl

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - dask
    - distributed
    - tornado
    - rich

test:
  requires:
    - python {{ python_min }}
  imports:
    - dask_ctl

about:
  home: https://github.com/dask-contrib/dask-ctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of tools to provide a control plane for managing the lifecycle of Dask clusters.
  description: |
    A set of tools to provide a control plane for managing the lifecycle of Dask clusters.
  doc_url: https://github.com/dask-contrib/dask-ctl
  dev_url: https://github.com/dask-contrib/dask-ctl

extra:
  recipe-maintainers:
    - jacobtomlinson
